### PR TITLE
Hotfix/prediction

### PR DESCRIPTION
**Pull request by iparask**
This PR closes issue #58.

To install on Bridges do:
```bash
iparask$ module load cuda
iparask$ module load python3
iparask$ virtualenv iceberg_seals
iparask$ source iceberg_seals/bin/activate
[iceberg_seals] iparask$ export PYTHONPATH= <path>/iceberg_seals/bin/activate:$PYTHONPATH
[iceberg_seals] iparask$ pip install . --upgrade
```

This should install everything. I also tested them but if you want to run the executables a way is:

```bash
[iceberg_seals] iparask$ iceberg_seals.tiling --scale_bands=299 --input_image=<image_abspath> --output_folder=./test
[iceberg_seals] iparask$ iceberg_seals.predicting --input_image=<image_filename> --model_architecture=UnetCntWRN --hyperparameter_set=A --training_set=test_vanilla --test_folder=./test --model_path=./ --output_folder=./test_image
```

Before running you should copy the model tarball in the same folder.

### CODE REVIEW

**Review by bspitzbart — COMMENTED** [review]
It installs fine, but I still get: (on bridges)
```
(iceberg_seals) [bspitz@login006 bspitz]$ iceberg_seals.predicting --help
Traceback (most recent call last):
  File "/pylon5/mc3bggp/bspitz/iceberg_seals/bin/iceberg_seals.predicting", line 19, in <module>
    from utils.model_library import *
ImportError: No module named 'utils'
```

**Comment by iparask** [comment]
Can you verify that you installed from `hotfix/prediction` branch? I think that is the issue.

**Comment by bspitzbart** [comment]
Oh yeah. Serious Monday here.
Now I get this inside git, but it installs if I copy the repo to a non git directory :
(iceberg_seals) [bspitz@login006 Seals]$ git checkout hotfix/prediction
Already on 'hotfix/prediction'
(iceberg_seals) [bspitz@login006 Seals]$ pip install . --upgrade
Processing /pylon5/mc3bggp/bspitz/Seals
ERROR: Could not install packages due to an EnvironmentError: [('/pylon5/mc3bggp/bspitz/Seals/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.pack', '/tmp/pip-req-build-njgdzb9w/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-njgdzb9w/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.pack'"), ('/pylon5/mc3bggp/bspitz/Seals/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.idx', '/tmp/pip-req-build-njgdzb9w/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-njgdzb9w/.git/objects/pack/pack-5f593a3e4189c1763a58b1d2b8b93e5d9f283835.idx'")]

**Comment by iparask** [comment]
Still Bridges, I'm afraid. Can you use a repo clone from your home directory? I do not know why this is happening.

**Comment by bspitzbart** [comment]
Install works from home directory. Now:
(iceberg_seals) [bspitz@login005 Seals]$ iceberg_seals.predicting --help
Traceback (most recent call last):
  File "/home/bspitz/iceberg_seals/bin/iceberg_seals.predicting", line 14, in <module>
    import torch
  File "/home/bspitz/iceberg_seals/lib/python3.5/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

**Comment by bspitzbart** [comment]
On Seawulf and $SCRATCH on bridges, I had to install scipy separately, but otherwise looks good.

**Comment by iparask** [comment]
You shouldn't. It should have picked `numpy 1.17` automatically. Can you verify that numpy 1.17 gets installed and what is your environment on Bridges? I haven't tried it on Seawulf, but the setup should install everything that is necessary.

**Comment by bspitzbart** [comment]
numpy is installed, but not scipy:
Installing collected packages: numpy, torch, pillow, torchvision, protobuf, tensorboardX, opencv-python, munch, attrs, fiona, pytz, pandas, aenum, pyproj, shapely, geopandas, iceberg-seals.search

Package              Version    
-------------------- -----------
aenum                2.2.1      
affine               2.2.0      
anvio                2.2.2      
attrs                19.1.0     
bleach               2.1.2      
bottle               0.12.13    
CherryPy             8.9.1      
click                6.7        
click-plugins        1.0.3      
cligj                0.4.0      
Cython               0.25.2     
decorator            4.0.6      
Django               1.10.6     
entrypoints          0.2.3      
ete3                 3.0.0b35   
Fiona                1.8.6      
GDAL                 1.11.0     
geopandas            0.5.1      
h5py                 2.6.0      
html5lib             1.0.1      
iceberg-seals.search 1.2.1      
ipykernel            4.8.1      
ipython              6.2.1      
ipython-genutils     0.1.0      
ipywidgets           7.1.2      
jedi                 0.11.1     
Jinja2               2.8        
jsonschema           2.6.0      
jupyter              1.0.0      
jupyter-client       5.2.2      
jupyter-console      5.2.0      
jupyter-core         4.4.0      
MarkupSafe           0.23       
mistune              0.8.3      
munch                2.3.2      
nbconvert            5.3.1      
nbformat             4.4.0      
nose                 1.3.7      
notebook             5.4.0      
numpy                1.12.0b1   
opencv-python        4.1.0.25   
pamela               0.2.1      
pandas               0.24.2     
pandocfilters        1.4.2      
parso                0.1.1      
pexpect              4.4.0      
pickleshare          0.7.4      
Pillow               6.1.0      
pip                  10.0.1     
prompt-toolkit       1.0.15     
protobuf             3.9.0      
psutil               5.2.0      
ptyprocess           0.5.2      
Pygments             2.2.0      
pyparsing            2.2.0      
pyproj               2.2.1      
pysam                0.9.1.4    
python-dateutil      2.6.1      
pytz                 2019.2     
pyzmq                17.0.0     
qtconsole            4.3.1      
rasterio             0.36.0     
requests             2.13.0     
scikit-learn         0.18.1     
scipy                0.18.1     
Send2Trash           1.5.0      
setuptools           20.10.1    
Shapely              1.6.4.post2
simplegeneric        0.8.1      
six                  1.10.0     
snuggs               1.4.1      
SQLAlchemy           1.0.11     
tensorboardX         1.8        
terminado            0.8.1      
testpath             0.3.1      
torch                1.1.0      
torchvision          0.3.0      
tornado              4.3        
traitlets            4.3.2      
virtualenv           15.1.0     
wcwidth              0.1.7      
webencodings         0.5.1      
wheel                0.29.0     
widgetsnbextension   3.1.4

**Comment by iparask** [comment]
Apparently, I had an error at the instructions where the python path was exported. As far as I know there is no dependency to scipy, but numpy. Am I missing something?

**Comment by bspitzbart** [comment]
predicting looks for scipy:

(seals) [bspitzbart@login2 seals]$ iceberg_seals.predicting --help
Traceback (most recent call last):
  File "/gpfs/scratch/bspitzbart/seals/bin/iceberg_seals.predicting", line 19, in <module>
    from iceberg_seals.search.utils.model_library import *
  File "/gpfs/scratch/bspitzbart/seals/lib/python3.7/site-packages/iceberg_seals/search/utils/model_library.py", line 16, in <module>
    from .dataloaders import *
  File "/gpfs/scratch/bspitzbart/seals/lib/python3.7/site-packages/iceberg_seals/search/utils/dataloaders/__init__.py", line 3, in <module>
    from .transforms_det_resized import ShapeTransform
  File "/gpfs/scratch/bspitzbart/seals/lib/python3.7/site-packages/iceberg_seals/search/utils/dataloaders/transforms_det_resized.py", line 8, in <module>
    from scipy import ndimage
ModuleNotFoundError: No module named 'scipy'

**Comment by iparask** [comment]
Now, that I did not know. I'll add it in the setup dependencies.

**Comment by iparask** [comment]
Okay now scipy is also installed.

**Comment by bspitzbart** [comment]
Looks good on Seawulf and $SCRATCH on bridges.
I still get this for my home dir installation, which I do not know why it would be any different than installing in $SCRATCH.
(iceberg_seals) [bspitz@login005 ~]$ iceberg_seals.predicting --help
Traceback (most recent call last):
  File "/home/bspitz/iceberg_seals/bin/iceberg_seals.predicting", line 14, in <module>
    import torch
  File "/home/bspitz/iceberg_seals/lib/python3.5/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

**Comment by iparask** [comment]
Did you get any errors during installation? This is very weird indeed.

**Comment by bspitzbart** [comment]
No, it installed normally.

**Comment by iparask** [comment]
Okay, can you activate your virtualenv and do:
```
export PYTHONPATH=<path_to_env>/lib/python3.5/site-packages:$PYTHONPATH
python -c "import numpy;print(numpy.__version__)"
```

and let me know what version of numpy you have? This is really weird, because I do not see it.

**Comment by bspitzbart** [comment]
[bspitz@login005 ~]$ source iceberg_seals/bin/activate
(iceberg_seals) [bspitz@login005 ~]$ export PYTHONPATH=/home/bspitz/lib/python3.5/site-packages:$PYTHONPATH
(iceberg_seals) [bspitz@login005 ~]$ python -c "import numpy;print(numpy.__version__)"
1.17.0

**Review by bspitzbart — APPROVED** [review]
I think we can merge this and push to pypi.  We will keep an open issue of my problem installing in $HOME, but no one else sees the problem and it installs and runs fine in $SCRATCH (on bridges and seawulf)

**Comment by iparask** [comment]
Can you give it last try where PYTHONPATH is set as:
```
PYTHONPATH=<path_to_ve>/lib/python3.5/site-packages/
```

I think it has to do with some configuration difference from Bridges between our accounts that I would like to remove.

**Comment by bspitzbart** [comment]
Yes! It worked!

**Comment by iparask** [comment]
Perfect! I'll release then!

**Comment by bspitzbart** [comment]
Great job. Thanks.

**Pull request merged**
