### PR TITLE
Breaking output folder structure

### PR DESCRIPTION
**Pull request by iparask**
This PR tries to destroy the hardwired folder structure in the prediction and tiling scripts.

The reasoning behind such change is to reduce the length of the path that leads to the tiles in the input as well as the output. 

I want to do the same with the prediction files. It would help with integrating with EnTK. Do you have any objections?

Thank you

Fixes issues #34, #24.

### CODE REVIEW

**Review by bspitzbart — COMMENTED** [review]
Bento - Is Pipeline 1.1 still correct or does it matter?  Otherwise, this looks great with the pathnames not hardcoded.

**Comment by bentocg** [comment]
@bspitzbart No, Pipeline1.1 is not necessary, I think I left it there by mistake.

**Comment by bspitzbart** [comment]
@iparask Have you run this and gotten any output?

**Comment by iparask** [comment]
@bspitzbart, I did a test run yesterday. I got some memory errors from tiling. I am trying to replicate and fix, but Bridges I am not able to correctly launch RP on Bridges. I think it is because Bridges and not something that has to do with the stack. I will update as I get more results.

**Comment by iparask** [comment]
Fixes issues #34, #24.

**Pull request merged**
