### PR TITLE
Saved models to devel

### PR DESCRIPTION
**Pull request by iparask**
Devel requires the changes in the saved models branch to further continue the integration with EnTK.

Although there are conflicts with the saved models branch.
@bentocg can you see and propose how these conflicts can be resolved? Without being able to merge any development we do may create bugs that are difficult to find due to wrong merges.

@bspitzbart Any suggestions on how to do this?

Thank you both,
Giannis

### CODE REVIEW

**Comment by iparask** [comment]
May I also suggest to remove the `.idea` , `.ipynb_checkpoints`, `__pychache__`, and any other folder that will be generated and updated in every run from the repo?

**Comment by iparask** [comment]
In addition, what are these 250k files that have changed? If they are data, would it be better to have them in a web server and not commit them in Git? Apart from making the checkout slow, it makes the repo difficult to maintain.

**Comment by bentocg** [comment]
Hi Giannis,

Yeah, the repo needs some cleanup and we need to add a lot of things to the .gitignore. It's good to get a second opinion on that. Brad created the saved_models branch because I asked him to change a few things and he didn't want to mess up with the rest of my code. I continued to work on that branch because I was too sloppy to merge with master but that is the real master now. I think we need to clean up saved_models and merge it with master before doing anything else . As of now, saved_models is working fine, there is nothing really to debug on my side so I think we can force it if needed. Maybe @bspitzbart can figure how we should merge it (I'm leaving for a conference today).

Bento

**Comment by bspitzbart** [comment]
Yes, I am working on the merge.

**Pull request merged**
