### PR TITLE
Fix/kernels 34

### PR DESCRIPTION
**Pull request by bspitzbart**
This pull request addresses issue #34 and milestone block.
predict_raster_det.py is the kernel for predictions
tile_raster.py is the kernel for tiling (no changes)

Bento - are there other issues fixed with my import of the code from https://github.com/bentocg/seals_temp/blob/master/predict_raster_det.py?

### CODE REVIEW

**Review by iparask — APPROVED** [review]
I am okay with this PR. if @bentocg is also fine let's merge and I will try to test the entk script with these changes.

**Comment by bentocg** [comment]
That will work. I can also add the shapefile output to predict_patch, I think that's what @iparask  would prefer in the first place.

**Review by bentocg — APPROVED** [review]

**Comment by iparask** [comment]
Hello @bentocg, I think that is what is needed as the ouput, right? Can you please do that and submit a new PR? I want to test the final script as soon as possible to catch the milestone.

**Comment by bentocg** [comment]
It needs some testing, but I think it has the correct output now. I'll push
to the temp repo and maybe Brad and I can test it.

Em seg, 10 de dez de 2018 às 17:08, Ioannis Paraskevakos <
notifications@github.com> escreveu:

**Comment by iparask** [comment]
There is no need to use the temp branch. Branch off devel and test there. It will end up in devel in the end. It will also help avoid conflicts.

**Pull request merged**
