### PR TITLE
Feature/entk v0.7.3

### PR DESCRIPTION
**Pull request by iparask**
This PR updates the EnTK script to the latest EnTK version.

### CODE REVIEW

**Review by bspitzbart — COMMENTED** [review]
Thanks. The code looks fine, mostly changes in naming conventions.  It is great to see a version number, but there is a discrepancy between the description 0.7.3 and the branch name 0.7.2.
Is there test data showing the same seal counts as previous versions (we still need to identify test images to cover various cases, false positives, false negatives, etc.)? Performance data?

**Comment by iparask** [comment]
Hello Brad,

Thank you for the review. The discrepancy is because EnTK's version has changed from the time the branch was created from 0.7.2 to 0.7.3.

The results are the same between the version that now is on devel and this one. 

This is the [CSV file](http://js-157-203.jetstream-cloud.org:9999/edit/ICEBERG/Seals/EnTKdevel/P0_WideResnetCount_predictions.csv) for `WV03_20141107053034_1040010004196C00_14NOV07053034-P1BS-500248187200_01_P005_u08rf3031.tif`. You can check if it is the expected result.

I do not have any performance data with this version of EnTK yet. The data I reported last time are from the previous version of EnTK

**Comment by bspitzbart** [comment]
Hi Giannis, Where can I find the jpg files referenced in the cvs file?
I am looking around  js-157-203.jetstream-cloud.org:9999/tree/ICEBERG/, but do not see them. Thanks

**Comment by iparask** [comment]
It is one of the tiff files on Bridges that you shared.

**Comment by bspitzbart** [comment]
I mean the individual tiles that are created from the large tif and are listed in the CSV file. Do you save those?

**Comment by iparask** [comment]
You can find them here: `/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017749.0005/pilot.0000/unit.000000` under the folder `tiles`.

You should have access, but just in case please confirm.

**Comment by bspitzbart** [comment]
No permission. Can you add g+rx? Thanks.

**Comment by iparask** [comment]
Done, please check again!

**Comment by bspitzbart** [comment]
Still no go.  I think you will have to chmod -R the whole tree from parask down.

**Comment by bspitzbart** [comment]
I can see it now. Thanks.

**Pull request merged**
