### PR TITLE
Release PR

### PR DESCRIPTION
**Pull request by iparask**
This is the PR that will be merged when the Milestone is done

### CODE REVIEW

**Comment by iparask** [comment]
ping @bspitzbart  and @bentocg .

Did you manage to check the output?

**Comment by bspitzbart** [comment]
The output appears correct in that the expected files are produced.  We are still checking the scientific validity to be sure the algorithm is working. Both are necessary to pull to master.  We will report at tomorrow's meeting.

**Comment by iparask** [comment]
Thank you for letting me know!

**Comment by iparask** [comment]
@bspitzbart @bentocg can you submit your reviews? If both are approving the PR, I will merge it and create a new tag for the Seals use case!

**Review by bentocg — APPROVED** [review]
Output seems correct, we should go ahead and merge!

**Comment by bspitzbart** [comment]
Yeah! Thanks Giannis.

**Pull request merged**
