### PR TITLE
Restructuring repo

### LINKED ISSUE #25: Folder organization in the repo
I would like to suggest a new folder structure for this repo. I propose something like:

```
src -|
     | - EnTK script
     | - predicting
     | - tiling
     | - utils
models - | - Pipeline1
         | - Pipeline1.1
validation_suite -|
                  | - Pipeline1.1/data
                  | - Pipeline1/data
```

Any thoughts?

I think it will organise things a bit better and I will allow better structure.

### PR DESCRIPTION
**Pull request by iparask**
This PR closes #25.
I was not sure what to do with the code that still exists in the home directory. Please either suggest where to move it or feel free to do it.

Also, I would suggest that you check it out and see if I removed something that I shouldn't have removed.

### CODE REVIEW

**Comment by bspitzbart** [comment]
Thanks Giannis.  I notice that what is under validation_suite should be under src/training. The R scripts in the home dir also belong in src/training.  (if Bento agrees)
I understood validation_suite to be scripts checking that test outputs are as expected.

**Comment by iparask** [comment]
I was not sure what the scripts that @bentocg had there were doing, so I placed them somewhere based on my understanding.

I will move them under `src/training`

**Comment by iparask** [comment]
Hello Brad. I agree that the validation suite should be scripts and expected data output not for every part of the development. In my opinion that includes the pipeline script, the kernels and any script that is developed to support this use case.

Do you agree?

**Comment by bspitzbart** [comment]
@iparask This is a case where validation has two meanings.  First, it is a formal ML term used in model training:
    Training Dataset: The sample of data used to fit the model.
    Validation Dataset: The sample of data used to provide an unbiased evaluation of a model fit on the training dataset while tuning model hyperparameters. The evaluation becomes more biased as skill on the validation dataset is incorporated into the model configuration.

Second is our validation_suite (maybe it should be verification_suite) on the predict pipeline. Here we want to compare non-EnTK output with the EnTK pipeline output using matching input test datasets.
    Test Dataset: The sample of data used to provide an unbiased evaluation of a final model fit on the training dataset.

validation/verification_suite can also contain unit tests for both the pipeline and kernels such as 1) are all resources available? 2) Is directory structure correct?

Does that clarify?  It seems to be consistent with issue #17 Create a validation suite?

**Pull request merged**
